'use client';
import { useState } from 'react';

export default function DownloadPDF({ data }: { data: any }) {
  const [loading, setLoading] = useState(false);

  const download = async () => {
    setLoading(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      let y = 20;

      doc.setFontSize(20);
      doc.setTextColor(37, 99, 235);
      doc.text('MedicalPlain — Clinical Analysis Report', 20, y);
      y += 10;

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('Generated by MedicalPlain AI — medicalplain.vercel.app', 20, y);
      y += 10;
      doc.text('Date: ' + new Date().toLocaleDateString(), 20, y);
      y += 15;

      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text('SUMMARY', 20, y);
      y += 8;
      doc.setFontSize(10);
      const summaryLines = doc.splitTextToSize(data.summary || '', 170);
      doc.text(summaryLines, 20, y);
      y += summaryLines.length * 6 + 10;

      if (data.overallRiskScore) {
        doc.setFontSize(12);
        doc.text('OVERALL RISK: ' + data.overallRiskScore.toUpperCase(), 20, y);
        y += 15;
      }

      if (data.medications?.filter((m: any) => m.name).length > 0) {
        doc.setFontSize(12);
        doc.setTextColor(37, 99, 235);
        doc.text('MEDICATIONS', 20, y);
        y += 8;
        data.medications.filter((m: any) => m.name).forEach((med: any) => {
          if (y > 260) { doc.addPage(); y = 20; }
          doc.setFontSize(11);
          doc.setTextColor(0, 0, 0);
          doc.text(med.name + ' — ' + (med.dosage || ''), 20, y);
          y += 6;
          doc.setFontSize(9);
          doc.setTextColor(60, 60, 60);
          if (med.purpose) { const lines = doc.splitTextToSize('Purpose: ' + med.purpose, 170); doc.text(lines, 25, y); y += lines.length * 5; }
          if (med.bestTimeToTake) { doc.text('When to take: ' + med.bestTimeToTake, 25, y); y += 5; }
          if (med.importantNote) { const lines = doc.splitTextToSize('Important: ' + med.importantNote, 170); doc.text(lines, 25, y); y += lines.length * 5; }
          y += 5;
        });
      }

      if (data.labValues?.filter((l: any) => l.testName).length > 0) {
        if (y > 220) { doc.addPage(); y = 20; }
        doc.setFontSize(12);
        doc.setTextColor(37, 99, 235);
        doc.text('LAB RESULTS', 20, y);
        y += 8;
        data.labValues.filter((l: any) => l.testName).forEach((lab: any) => {
          if (y > 260) { doc.addPage(); y = 20; }
          doc.setFontSize(10);
          doc.setTextColor(0, 0, 0);
          doc.text(lab.testName + ': ' + lab.value + ' (' + (lab.status || '').toUpperCase() + ')', 20, y);
          y += 5;
          doc.setFontSize(9);
          doc.setTextColor(60, 60, 60);
          if (lab.plainExplanation) { const lines = doc.splitTextToSize(lab.plainExplanation, 170); doc.text(lines, 25, y); y += lines.length * 5; }
          y += 3;
        });
      }

      if (data.questionsToAsk?.length > 0) {
        if (y > 220) { doc.addPage(); y = 20; }
        doc.setFontSize(12);
        doc.setTextColor(37, 99, 235);
        doc.text('QUESTIONS TO ASK YOUR DOCTOR', 20, y);
        y += 8;
        data.questionsToAsk.forEach((q: string, i: number) => {
          if (y > 260) { doc.addPage(); y = 20; }
          doc.setFontSize(10);
          doc.setTextColor(0, 0, 0);
          const lines = doc.splitTextToSize((i + 1) + '. ' + q, 170);
          doc.text(lines, 20, y);
          y += lines.length * 6;
        });
      }

      y += 10;
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(data.disclaimer || 'This is for educational purposes only. Always consult your doctor.', 20, y);

      doc.save('MedicalPlain-Report-' + new Date().toLocaleDateString().replace(/\//g, '-') + '.pdf');
    } catch (error) {
      console.error(error);
      alert('PDF generation failed. Please try again.');
    }
    setLoading(false);
  };

  return (
    <button onClick={download} disabled={loading}
      className="bg-purple-600 text-white font-semibold py-3 rounded-xl text-sm hover:bg-purple-700 disabled:opacity-50 w-full">
      {loading ? '⏳ Generating PDF...' : '📄 Download PDF Report'}
    </button>
  );
}
